dataset:
  image_dir: /content/drive/MyDrive/CarDD_release/CarDD_SOD/CarDD-TR/CarDD-TR-Image
  mask_dir: /content/drive/MyDrive/CarDD_release/CarDD_SOD/CarDD-TR/CarDD-TR-Mask
  train_split: /content/Segment-Damage/data/splits/train.json
  val_split: /content/Segment-Damage/data/splits/val.json
  test_split: /content/Segment-Damage/data/splits/test.json
  image_size: 512
  class_labels_file: null
  default_class_label: 0
  infer_class_from_mask: false
model:
  name: mask2former
  num_classes: 2
  pretrained_model_name: facebook/mask2former-swin-tiny-ade-semantic
training:
  epochs: 5
  batch_size: 2
  lr: 0.0001
  weight_decay: 0.0001
  loss:
    name: ce_dice_focal
    use_gradient: true
    gradient_foreground_class: 1
    focal_gamma: 2.0
    focal_alpha: 0.25
    weights:
      ce: 1.0
      dice: 1.0
      focal: 1.0
      grad: 1.0
      contrastive: 0.0
      cls: 0.0
      cls_contrastive: 0.0
    contrastive:
      enabled: false
      foreground_class_index: 1
      tiny_area_threshold_pixels: 2048
      temperature: 0.1
      max_tiny_samples: 1024
      max_other_samples: 4096
      min_tiny_pixels: 16
    classification:
      enabled: false
      multilabel: true
      threshold: 0.5
      class_contrastive:
        enabled: false
        temperature: 0.1
    class_weights:
    - 1.0
    - 4.0
  scheduler:
    name: cosine_annealing
    t_max: 5
    eta_min: 1.0e-06
    factor: 0.5
    patience: 3
    mode: min
    threshold: 0.0001
    threshold_mode: rel
    cooldown: 0
    min_lr: 1.0e-06
  num_workers: 2
  output_dir: my_results_folder/mask2former_output/mask2former_tiny
  visualize_every: 10
  visualize_samples: 3
  tensorboard: true
  tensorboard_dir: my_results_folder/mask2former_output/mask2former_tiny/tensorboard
